name: CI

on: [push, pull_request]

jobs:
  build_and_check:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown

    name: Build Check ${{ matrix.target }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: check build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target ${{matrix.target}} --no-default-features --features=reqwest-async

  test:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    name: Test ${{ matrix.target }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{matrix.target}}

      - name: test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{matrix.target}} --all-features -- --test-threads 1

      - name: test --no-default-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{matrix.target}} --no-default-features
